### ISSUE TITLE
Collision issue in the south-western map

### ISSUE THREAD

**Issue by PhoenixII54** [christopho/zelda_roth_se#92] opened 2015-12-20 13:31 UTC
On the path to hidden dungeon, you can get stuck in the wall on the legt right after grappling over the gap. Just walk/run to the left and voilà.

Probable cause : mis-levelling of the wall tile.

Proof : 
![20151220_141339](https://cloud.githubusercontent.com/assets/10976783/11918162/123af7fc-a726-11e5-833e-6ffe7408ebb1.jpg)

NB : picture taken with the smartphone of a cousin, so sorry for the bad quality.

**Comment by christopho** [comment] 2015-12-20 13:35
Duplicate of #87

**Closed as completed by christopho** 2015-12-20 13:35 UTC
Labels: duplicate
