### ISSUE TITLE
Teleporter not working on the left of the secret dungeon

### ISSUE THREAD

**Issue by Renkineko** [christopho/zelda_roth_se#54] opened 2015-08-13 19:01 UTC
Do go back to the monster village, you can take a shortcut here : 

![image](https://cloud.githubusercontent.com/assets/2254151/9258907/636296d6-41fe-11e5-8b74-35394d6222f4.png)

The teleporter is not active.

**Comment by Renkineko** [comment] 2015-08-13 19:04
No way to come back by the same path, there is a dead end (first time you use the hookshot on this path).

**Comment by christopho** [comment] 2015-08-13 19:23
Duplicate of #51

**Closed as completed by christopho** 2015-08-13 19:23 UTC

**Comment by Renkineko** [comment] 2015-08-13 21:03
Yep, saw it after... And it's on the right, I'm so dumb xD
